#!/usr/bin/env python3
"""Run the reference testbed and write (or check) the recorded answers.

    python3 testbed/run.py            # rewrite testbed/answers.md
    python3 testbed/run.py --check    # fail if the answers have drifted

The point is not that yqr agrees with these libraries. It is that when a
design question comes up -- whose comment is this, is that document one
anybody else reads, what should an emptied block become -- the answer is
measured against implementations people actually run, and the measurement
is dated, versioned and reproducible instead of recalled.

See specs/implementation/yqr-m007-reference-testbed.md.
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ADAPTERS = HERE / "adapters"

# Ordered: the three that answer "what does this mean", then the two that
# also answer "where does this comment go".
PEERS = [
    ("PyYAML", [sys.executable, str(ADAPTERS / "pyyaml_adapter.py")]),
    ("Psych", ["ruby", str(ADAPTERS / "psych_adapter.rb")]),
    ("js-yaml", ["bun", "run", str(ADAPTERS / "jsyaml_adapter.ts")]),
    ("go-yaml", None),  # a built binary, filled in by build_go
    ("ruamel", [sys.executable, str(ADAPTERS / "ruamel_adapter.py")]),
]


def build_go(tmp: Path) -> list[str] | None:
    """Build the go-yaml adapter once rather than `go run` per call."""
    if shutil.which("go") is None:
        return None
    out = tmp / "goyaml"
    r = subprocess.run(
        ["go", "build", "-o", str(out), "."],
        cwd=ADAPTERS / "goyaml",
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        print(f"go-yaml adapter did not build:\n{r.stderr}", file=sys.stderr)
        return None
    return [str(out)]


def ask(cmd: list[str], req: dict) -> dict:
    """One question to one implementation."""
    try:
        r = subprocess.run(
            cmd, input=json.dumps(req), capture_output=True, text=True, timeout=60
        )
    except FileNotFoundError:
        return {"missing": f"{cmd[0]} is not installed"}
    except subprocess.TimeoutExpired:
        return {"error": "timed out"}
    line = r.stdout.strip().splitlines()
    if not line:
        return {"error": (r.stderr.strip().splitlines() or ["no output"])[-1]}
    try:
        return json.loads(line[-1])
    except json.JSONDecodeError:
        return {"error": line[-1]}


def visible(text: str) -> str:
    """The exact bytes, on one line, without markdown eating any of them."""
    return (
        text.replace("\\", "\\\\")
        .replace("\r", "\\r")
        .replace("\n", "\\n")
        .replace("`", "\u2019")
        .replace("|", "\\|")
    )


def render(answer: dict) -> str:
    """One cell of the report."""
    if "missing" in answer:
        return f"_{answer['missing']}_"
    if "unsupported" in answer:
        return f"_unsupported: {answer['unsupported']}_"
    if "error" in answer:
        return f"**refused** `{visible(answer['error'])}`"
    return "`" + visible(answer["result"]) + "`"


def main() -> int:
    check = "--check" in sys.argv
    import yaml  # PyYAML, which the testbed requires anyway

    cases = yaml.safe_load((HERE / "cases.yaml").read_text())
    with tempfile.TemporaryDirectory() as td:
        peers = [(n, build_go(Path(td)) if c is None else c) for n, c in PEERS]
        peers = [(n, c) for n, c in peers if c is not None] or []
        versions = []
        for name, cmd in peers:
            v = ask(cmd, {"op": "version"})
            versions.append(f"| {name} | {v.get('version', v.get('missing', '?'))} |")

        out = [
            "# Reference testbed: recorded answers",
            "",
            "Generated by `python3 testbed/run.py`. Do not edit by hand.",
            "",
            "Each row is one implementation's answer to one question about one",
            "document. A refusal is an answer, and so is `unsupported`: it is why a",
            "comment question cannot be settled by citing PyYAML.",
            "",
            "| implementation | version |",
            "|---|---|",
            *versions,
            "",
        ]
        for case in cases:
            out += [f"## {case['id']}", "", case["why"].strip(), "", "```yaml",
                    case["source"].replace("\r\n", "\\r\\n ->\n"), "```", ""]
            if "path" in case:
                out += [f"Path: `{json.dumps(case['path'])}`", ""]
            for op in case["ops"]:
                out += [f"### {op}", "", "| implementation | answer |", "|---|---|"]
                for name, cmd in peers:
                    a = ask(cmd, {"op": op, "source": case["source"],
                                  "path": case.get("path")})
                    out.append(f"| {name} | {render(a)} |")
                out.append("")

        text = "\n".join(out) + "\n"

    target = HERE / "answers.md"
    if check:
        if not target.exists():
            print("no recorded answers; run without --check first", file=sys.stderr)
            return 1
        if target.read_text() != text:
            print("the testbed's answers have drifted from the record.", file=sys.stderr)
            print("Re-run without --check, read the diff, and record why.", file=sys.stderr)
            return 1
        print("testbed: answers match the record")
        return 0
    target.write_text(text)
    print(f"testbed: wrote {target.relative_to(HERE.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
